# Generated by Django 3.2.6 on 2021-10-30 17:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category name')),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('advantages', models.TextField(blank=True, max_length=500, null=True)),
                ('disadvantages', models.TextField(blank=True, max_length=500, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcomments', to='product.comment')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('slug', models.SlugField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product price')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('screen_resolution', models.CharField(max_length=255, verbose_name='Screen resolution')),
                ('screen_type', models.CharField(max_length=255, verbose_name='Screen type')),
                ('processor', models.CharField(max_length=255, verbose_name='Processor')),
                ('ram', models.CharField(max_length=255, verbose_name='RAM')),
                ('drive_type', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD')], max_length=50)),
                ('video', models.CharField(max_length=255, verbose_name='Video memory')),
                ('battery', models.CharField(max_length=255, verbose_name='Battery amount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Category')),
                ('comments', models.ManyToManyField(blank=True, null=True, to='product.Comment')),
            ],
            options={
                'ordering': ('-date_added',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('slug', models.SlugField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product price')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('screen_resolution', models.CharField(max_length=255, verbose_name='Screen resolution')),
                ('screen_type', models.CharField(max_length=255, verbose_name='Screen type')),
                ('processor', models.CharField(max_length=255, verbose_name='Processor')),
                ('ram', models.CharField(max_length=255, verbose_name='RAM')),
                ('drive_type', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD')], max_length=50)),
                ('video', models.CharField(max_length=255, verbose_name='Video memory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Category')),
                ('comments', models.ManyToManyField(blank=True, null=True, to='product.Comment')),
            ],
            options={
                'ordering': ('-date_added',),
                'abstract': False,
            },
        ),
    ]
