# Generated by Django 3.2.6 on 2021-11-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211105_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.ManyToManyField(related_name='_product_comment_comment_+', to='product.Comment'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='comments',
            field=models.ManyToManyField(to='product.Comment'),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='comments',
            field=models.ManyToManyField(to='product.Comment'),
        ),
    ]
