# Generated by Django 3.2.6 on 2021-11-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211105_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='product.Comment'),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='product.Comment'),
        ),
    ]
